# Generated by Django 5.0.1 on 2024-01-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0002_user_address_user_city_user_pincode_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
