# Generated by Django 5.0.1 on 2024-01-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0006_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
